---
:layout: default
:icons:
---
== Hello

[.lead]
My name is Conner Kulbaski, and I'm a Computer Science student at the University of Manitoba. I'm currently seeking employment in the field of computer science, software development, or IT. Contact me at connerkulbaski@gmail.com! +

== Personal Details

[horizontal]
Name:: Conner Kulbaski
Contacts::
- connerkulbaski@gmail.com
- https://github.com/ckulbaski

== Education
`2017 - present` +
*Bachelor of Science - Computer Science (Honours) (ongoing)* +
*University of Manitoba*
  
  
=== Skills

- Certified in Micosoft Azure Fundamentals
- Microsoft DevOps
- Java, C, Python, Javascript
- UX/Front-end development using React and Bootstrap
- Agile software development
- Git/version control
- Static website building
- Excellent teamwork and communication skills
- Speaks french

== Projects

=== Mindful.ly
- https://github.com/scottjodoin/gratitude-prototype

This is a prototype for a mindfulness/gratitude app made for COMP 3020 (Human-Computer Interaction). It's written in Javascript and Bootstrap, and uses Chart.js to display the data.
The purpose of this project was to design a good user interface, rather than making a functional app, which is why the data is hard coded and static. 

=== "BudgeIt" Android app

My team and I used Agile software development to develop an app that is used to track spending and saving habits. We worked in Android Studio, which was part of a project for Software Engineering 1.  

=== SEO-ker
- https://seoker.herokuapp.com/

My Software Engineering 2 project was a multiplayer party game inspired by [Higher Lower Game](https://www.higherlowergame.com/) and poker. It was built using [Next.js](https://nextjs.org/), [Socket.io](https://socket.io/), and [MongoDB](https://www.mongodb.com/).

== Work Experience

I don't have any experience working in the computer science/software development industry right now. However, I have lots of experience that demonstrates that I am a good team member and have excellent communication skills. 

=== Manitoba Hydro - Digital & Technology Trainee program
`May 2022 - Present` +

Manitoba Hydro's D&T Trainee program rotates new graduates through 4 different fields over the course of 2 years, giving each employee experience in a new department every 6 months. 
- Data & Analytics. 
	- Earned certification in Microsoft Azure Fundamentals, Microsoft's cloud platform that Hydro is currently transitioning to. 
	- IBM COGNOS migration project. Developed reports in Microsoft Power BI to replace IBM COGNOS, which was becoming obsolete. 
	- Peakload Report Prototyping. Developed prototypes in Power BI as a proof-of-concept. The business was investigating the capabilities of Power BI to visualize real-time data from Aveva PI sensors in the field. 
- System Support.
	- UnitCyclingTool. This is an advisory tool built using ReactJS for the front end and C# for the back end. It is used by system operators to track which generation units were most recently turned on/off to reduce wear and tear. 
		- Debugged the tool to allow it to run successfully on the development server
		- Configured a DevOps pipeline to build and deploy the tool to Dev and Prod servers
		- Fixed miscellaneous UI bugs

=== Winnipeg School Division
`May - August in 2019, 2020, and 2021` +

I was a summer groundskeeper for all 78 schools in the Winnipeg School Division 1. I lead a team of students to cut grass, trim hedges, fix fences, aerate and soil fields, and many other groundskeeping tasks. 

=== University of Manitoba Recreation Services - Referee  
`September 2019 - March 2020` +

I reffed intramural dodgeball and water polo games held at the Active Living Centre in the University of Manitoba.  

=== Windsor Plywood - Sales
`August 2017 - April 2019` +

As a sales person I was responsible for quoting and selling lumber, hardware, doors, etc, as well as maintaining the store and lumber yard. This includes tasks like picking and packing large orders, stocking product racks, and building new product displays. I was hired as a lumber yard attendant, and was promoted to sales person after 1 year of employment.

=== Feel Good Café
`September 2015 - March 2017` +

I was responsible for preparing a variety of hot and cold meals, including breakfast and lunch, in a kitchen environment. I also provided excellent customer service while operating the cash register. 


=== Me to We Service Learning Trip
`March 2017` +

In my senior year of high school I spent 10 days in Tanzania immersing myself in Maasai culture. We helped build a school, and our money went towards building a well in a rural village. One of the greatest experiences of my life, I hope to return some day!


